cd /root/
rm -rf Lindacoin
rm -rf https://github.com/Lindacoin/Linda/releases/download/2.0.0.1/Unix.Lindad.v2.0.0.1g.tar.gz
echo " "
echo " "
echo " "
echo " "
echo " "
echo "NerdyUser: Clean up script completed!"
echo "NerdyUser: You can now bootstrap your VPS by FileZilla!"
echo "NerdyUser: ------------------------"
Lindad stop
echo "NerdyUser: ------------------------"
echo "NerdyUser: If you just got an error between the striped lines, ignore it."
echo "NerdyUser: Just a verification step to be sure your masternode isn't running"
echo "NerdyUser: before you bootstrap it."
echo " "
echo " "
echo " "
echo " "
echo " "
echo "NerdyUser: Perform by yourself: cd /root/"
echo "NerdyUser: before you continue"
echo " "
echo " "
echo " "
echo " "
echo " "