cd ~/
rm -rf Lindacoin
rm -rf https://github.com/Lindacoin/Linda/releases/download/2.0.0.1/Unix.Lindad.v2.0.0.1g.tar.gz
echo " "
echo " "
echo " "
echo " "
echo " "
echo "NerdyUser: Clean up script completed!"
echo " "
echo " "
echo " "
echo " "
echo " "
echo "NerdyUser: Perform by yourself: cd ~/"
echo "NerdyUser: before you continue"
echo " "
echo " "
echo " "
echo " "
echo " "
